name: Main Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout Meadow.Desktop.Samples
      uses: actions/checkout@v3
      with:
        path: Meadow.Desktop.Samples
        ref: main

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
      
    - name: Build Meadow.Windows.Samples
      run: dotnet build -c Release Meadow.Desktop.Samples/Source/Windows/Meadow.Windows.Samples.sln